steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=asia-south1-docker.pkg.dev/${PROJECT_ID}/docker-repo/${_SERVICE_NAME}'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--context=.'
      - '--dockerfile=./Dockerfile'
      - '--build-arg=PORT=8080'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=asia-south1-docker.pkg.dev/${PROJECT_ID}/docker-repo/${_SERVICE_NAME}'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--project=${PROJECT_ID}'

substitutions:
  _SERVICE_NAME: default-service-name
