# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

# Copy only package files first to leverage cache
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy rest of the application
COPY . .

# Production stage
FROM node:18-alpine

WORKDIR /app

# Copy only necessary files from builder
COPY --from=builder /app/node_modules/ ./node_modules/
COPY --from=builder /app/*.js ./
COPY --from=builder /app/templates/ ./templates/
COPY --from=builder /app/.env ./
COPY --from=builder /app/google_creds.json ./
COPY --from=builder /app/public/*.html ./public/


# Expose port
EXPOSE 8080

# Start the application
CMD [ "node", "receptionist.js" ]